[build]
  command="ng build"
  publish="dist/angular-quickstart"
  
  firebaseConfig = "aaa"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = false

  [plugins.inputs]
    enable = false