[build]
  command="ng build"
  publish="dist/angular-quickstart"
  
  firebaseConfig = "{
    apiKey: "AIzaSyCGEoJURKc7mhW7M-iPwSWlvWhlofB7Pcg",
    authDomain: "fridge-app-cool.firebaseapp.com",
    projectId: "fridge-app-cool",
    storageBucket: "fridge-app-cool.appspot.com",
    messagingSenderId: "230543031921",
    appId: "1:230543031921:web:3cb83d69bed2c35e7d65d0"
  }"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = false

  [plugins.inputs]
    enable = false